name: Health Check
on:
  schedule:
    - cron: '0/5 * * * *'
  
  workflow_dispatch:
    
jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
