name: Health Check

on:
  schedule:
    - cron: '0/1 * * * *'
  
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      - name: 'Execute check.sh'
        run: bash ./check.sh

      - name: 'Send Email'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 俱乐部告警
          body: file://check.json
          to: 875256050@qq.com
          form: github action
          content_type: text/json
