name: Health Check

on:
  schedule:
    - cron: '0/1 * * * *'
  
  workflow_dispatch:
  
jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Codes'
        uses: actions/checkout@v2

      - name: 'Health Check'
        id: tut
        run: |
          curl https://www.fansmeta.io/api/health/check -o health.json
          cat health.json
          code=$(cat health.json | sed 's/,/\n/' | grep 'code' | sed 's/:/\n/'| sed '1d'| sed 's/"//g')
          echo 'code:' $code
          if test $code==0;then
              echo "sendFlag=true" >>  $GITHUB_ENV
          else
              echo "sendFlag=false" >> $GITHUB_ENV
          fi
          rm -f health.json
          echo 'rm -f health.json'
          echo '变量：' ${{steps.tut.outputs.sendFlag}}
      - name: 'Send Email'
        run: |
           echo '1:'$sendFlag
        
      - name: 'send Email'
        if: ${{env.sendFlag}} == true
        run: echo '发送邮件'
