name: Health Check

on:
  schedule:
    # - cron: '0/1 * * * *'
  
  workflow_dispatch:
  
jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Codes'
        uses: actions/checkout@v2

      - name: 'Health Check'
        id: tut
        run: |
          curl https://www.fansmeta.io/api/health/check -o health.json
          cat health.json
          code=$(cat health.json | sed 's/,/\n/' | grep 'code' | sed 's/:/\n/'| sed '1d'| sed 's/"//g')
          echo 'code:' $code
          if test $code==0;then
              echo "sendFlag=true" >>  $GITHUB_ENV
          else
              echo "sendFlag=false" >> $GITHUB_ENV
          fi
          rm -f health.json
          echo 'rm -f health.json'

      - name: Check Send Email
        run: echo '是否需要发送告警邮件：' $sendFlag
        
      - name: 'send Email'
        if: ${{env.sendFlag}} == true
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 俱乐部告警
          body: '服务异常告警'
          to: ${{ secrets.MAIL_TO_USER }}
          from: 875256050@qq.com
